apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: vector-sample
  namespace: vector
spec:
  agent:
    image: timberio/vector:0.24.0-distroless-libc
    service: true
    env:
    - name: "LUX-LOG-ELASTIC-HOST"
      value: "lux-log.xbet.lan"
    - name: "LUX-LOG-ELASTIC-USER"
      value: "lux-write"
    - name: "LUX-LOG-ELASTIC-PASSWORD"
      value: "bieteuH3keileR}"
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/ingress
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
