apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vector-operator.name" . }}
  namespace: {{ include "vector-operator.namespace" . }} 
  labels:
    app.kubernetes.io/name: {{ include "vector-operator.name" . }} 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vector-operator.name" . }} 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vector-operator.name" . }} 
        app.kubernetes.io/managed-by: "helm"
        meta.helm.sh/release-name: {{ include "vector-operator.name" . }} 
    spec:
      volumes:
        - name: kube-api-access
          secret:
            secretName: vector-operator-sa-token
            defaultMode: 420
      automountServiceAccountToken: false
      serviceAccountName: {{ include "vector-operator.serviceAccountName" . }}   
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: vector-operator
        volumeMounts:
            - name: kube-api-access
              readOnly: true
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
{{- toYaml .Values.image.securityContext | nindent 10 }}     
         
    