{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vector-operator.serviceAccountName" . }} 
{{- if .Values.serviceAccount.annotations }}  
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}  
{{- end }}
secrets:
  - name: vector-operator-sa-token 
{{- end }}  