{{- if .Values.vector.create  -}}
apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: {{ .Values.vector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  agent:
    image: {{ .Values.vector.agent.image }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}        