apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vector-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterVectorPipeline is the Schema for the clustervectorpipelines
        API
      displayName: Cluster Vector Pipeline
      kind: ClusterVectorPipeline
      name: clustervectorpipelines.observability.kaasops.io
      version: v1alpha1
    - description: VectorPipeline is the Schema for the vectorpipelines API
      displayName: Vector Pipeline
      kind: VectorPipeline
      name: vectorpipelines.observability.kaasops.io
      version: v1alpha1
    - description: Vector is the Schema for the vectors API
      displayName: Vector
      kind: Vector
      name: vectors.observability.kaasops.io
      specDescriptors:
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          if not specified - default setting will be used
        displayName: Resources
        path: agent.configCheck.resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          if not specified - default setting will be used
        displayName: Resources
        path: agent.resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      version: v1alpha1
  description: The operator deploys and configures a vector agent daemonset on every
    node to collect container and application logs from the node file system
  displayName: vector-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - vector
  - observability
  - logging
  links:
  - name: Vector Operator
    url: https://vector-operator.domain
  maintainers:
  - email: info@kaasops.io
    name: kaasops
  maturity: alpha
  provider:
    name: kaasops.io
    url: https://kaasops.io/
  version: 0.0.0
