apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: vector-sample
  namespace: vector
spec:
  agent:
    image: "timberio/vector:0.28.1-debian"
    internalMetrics: false
    api:
      enabled: true
      healthcheck: true
