apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: clustervectorpipeline-sample
spec:
  sources:
    test1:
      type: "kubernetes_logs"
      extra_label_selector: "app!=testdeployment3"
  sinks:
    test2:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - test1