{{- if .Values.vector.enable  -}}
apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: {{ .Values.vector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  mergeKubernetesSources: {{ .Values.vector.mergeKubernetesSources}}
  mergeSinks: {{ .Values.vector.mergeSinks}}
{{- with .Values.vector.agent }}
  agent:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}