{{- if .Values.vector.enable  -}}
apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: {{ .Values.vector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  useApiServerCache: {{ .Values.vector.useApiServerCache }}
{{- if or .Values.vector.agent .Values.vector.image }}
  agent:
{{- with .Values.vector.agent }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.vector.image }}
    image: {{ include "vector.image" (dict "global" $.Values.global.image "image" . "defaultTag" .tag ) | quote }}
{{- end }}
{{- end }}
{{- end }}