{{- if .Values.vector.enable  -}}
apiVersion: observability.kaasops.io/v1alpha1
kind: Vector
metadata:
  name: {{ .Values.vector.name }}
  namespace: {{ .Release.Namespace }}
spec:
  useApiServerCache: {{ .Values.vector.useApiServerCache }}
  image: {{ include "vector.image" (dict "global" .Values.global.image "image" .Values.vector.image "defaultTag" .Values.vector.image.tag ) | quote }}
{{- with .Values.vector.agent }}
  agent:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}