apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2022-12-15T16:29:49.262088+02:00"
    description: A Helm chart to install Vector Operator
    digest: f4398224ce88b852b319c950d0f39bfd5e6181801c1fac1b42b069dd2d358078
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2022-12-15T16:29:49.264843+02:00"
    description: A Helm chart to install Vector Operator
    digest: 66c528b6daa9f6fb9a8dd91895b69151f3f0183f4685ba4a2bc026fac27f25a7
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2022-12-15T16:29:49.264108+02:00"
    description: A Helm chart to install Vector Operator
    digest: 21c4c214cd0206abb743e82ac757804d644de08d80eb5f2edbb82ff9668cfed3
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: v0.0.7
    created: "2022-12-15T16:29:49.263485+02:00"
    description: A Helm chart to install Vector Operator
    digest: 27915a2bf70da3f66d08cf4a1f6c41ad38937759ad52eaf8b19f5a3e348e2f2e
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: v0.0.6
    created: "2022-12-15T16:29:49.262854+02:00"
    description: A Helm chart to install Vector Operator
    digest: 26760fbc2018336c12e8726307a624970ee994c4ffa021cc216c13669bd82f09
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: v0.0.5
    created: "2022-12-15T16:29:49.261413+02:00"
    description: A Helm chart to install Vector Operator
    digest: 1d6034027ae2f08a9dbea4d6ee9a1604117ae44d9daceb3f654b87a99175251f
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2022-12-15T16:29:49.260393+02:00"
