apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: v0.0.4
    created: "2022-11-18T16:07:04.287469+02:00"
    description: A Helm chart to install Vector Operator
    digest: fdbed288236bb0fb02054ec4797df0dd51dc8f42872a0a5e50da12f256ab28db
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2022-11-18T16:07:04.286393+02:00"
