apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: v0.0.14
    created: "2023-03-28T16:57:26.273005421+03:00"
    description: A Helm chart to install Vector Operator
    digest: 7e9ec1ed91a9715c90f21ccb67b54aadfed56312d96f7fbee575e89fec013457
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v2
    appVersion: v0.0.13
    created: "2023-03-28T16:57:26.272425648+03:00"
    description: A Helm chart to install Vector Operator
    digest: c88a1866a20fb2aea4a23886e6e60080eba9ae7ef2706f492d9b329dc9ddf49b
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v2
    appVersion: v0.0.12
    created: "2023-03-28T16:57:26.271229019+03:00"
    description: A Helm chart to install Vector Operator
    digest: 384e8fd8f8f743036eaf1415d893158256a2ad9daddcb17a3d0701a528d9f0df
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v2
    appVersion: v0.0.11
    created: "2023-03-28T16:57:26.270488116+03:00"
    description: A Helm chart to install Vector Operator
    digest: 29e1e04c1706b88ef61ed6c91a45847e6069843419515a33046c5929b179e273
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.11.tgz
    version: 0.0.11
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2023-03-28T16:57:26.269900611+03:00"
    description: A Helm chart to install Vector Operator
    digest: f4398224ce88b852b319c950d0f39bfd5e6181801c1fac1b42b069dd2d358078
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2023-03-28T16:57:26.275296725+03:00"
    description: A Helm chart to install Vector Operator
    digest: 66c528b6daa9f6fb9a8dd91895b69151f3f0183f4685ba4a2bc026fac27f25a7
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2023-03-28T16:57:26.274704835+03:00"
    description: A Helm chart to install Vector Operator
    digest: 21c4c214cd0206abb743e82ac757804d644de08d80eb5f2edbb82ff9668cfed3
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: v0.0.7
    created: "2023-03-28T16:57:26.274150233+03:00"
    description: A Helm chart to install Vector Operator
    digest: 27915a2bf70da3f66d08cf4a1f6c41ad38937759ad52eaf8b19f5a3e348e2f2e
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: v0.0.6
    created: "2023-03-28T16:57:26.273587144+03:00"
    description: A Helm chart to install Vector Operator
    digest: 26760fbc2018336c12e8726307a624970ee994c4ffa021cc216c13669bd82f09
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: v0.0.5
    created: "2023-03-28T16:57:26.26928276+03:00"
    description: A Helm chart to install Vector Operator
    digest: 1d6034027ae2f08a9dbea4d6ee9a1604117ae44d9daceb3f654b87a99175251f
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2023-03-28T16:57:26.262627995+03:00"
