apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: v0.0.5
    created: "2022-11-19T13:43:20.908782+02:00"
    description: A Helm chart to install Vector Operator
    digest: 1d6034027ae2f08a9dbea4d6ee9a1604117ae44d9daceb3f654b87a99175251f
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2022-11-19T13:43:20.907993+02:00"
