apiVersion: v1
entries:
  vector-operator:
  - apiVersion: v2
    appVersion: v0.0.6
    created: "2022-11-23T09:53:26.922455+02:00"
    description: A Helm chart to install Vector Operator
    digest: 26760fbc2018336c12e8726307a624970ee994c4ffa021cc216c13669bd82f09
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: v0.0.5
    created: "2022-11-23T09:53:26.921796+02:00"
    description: A Helm chart to install Vector Operator
    digest: 1d6034027ae2f08a9dbea4d6ee9a1604117ae44d9daceb3f654b87a99175251f
    home: https://github.com/kaasops/vector-operator
    name: vector-operator
    sources:
    - https://github.com/kaasops/vector-operator
    type: application
    urls:
    - https://kaasops.github.io/vector-operator/helm/packages/vector-operator-0.0.1.tgz
    version: 0.0.1
generated: "2022-11-23T09:53:26.920962+02:00"
